#Pandas concat excel 多种操作方法

In [1]:
import pandas as pd
dict=[[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8],[4,5,6,7,8,9],[5,6,7,8,9,10]]

In [2]:
data = pd.DataFrame(dict)

In [3]:
data

0  1  2  3  4   5
0  1  2  3  4  5   6
1  2  3  4  5  6   7
2  3  4  5  6  7   8
3  4  5  6  7  8   9
4  5  6  7  8  9  10

In [4]:
for indexs in data.index:
    print(data.loc[indexs].values[0:-1])

[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [10]:
import os
import pandas as pd 
dir = 'test/'
filenames = os.listdir(dir)
index = 0
dfs = []
for name in filenames:
    print(index)
    dfs.append(pd.read_excel(os.path.join(dir,name)))
    index +=1
df = pd.concat(dfs)
df.to_excel('data/total.xlsx',index= False)   不可用

SyntaxError: invalid syntax (<ipython-input-10-62067f91a10c>, line 10)

In [11]:
import tkinter.filedialog as tkFD
 
def __init__(self, root):
    self.ext1 = Button(self.frame[1], text="选择文件", command=self.openfile,width = 10)
        self.ext1.pack(side = LEFT, padx = 2,pady = 10)
        self.txt = Text(self.frame[1],height = 1,width = 80)
        self.txt.pack(side = LEFT, padx = 2,pady = 10)
 
        self.ext3 = Button(self.frame[3], text="选择根目录", command=self.opendir,width = 10)
        self.ext3.pack(side = LEFT, padx = 2,pady = 10)       
        self.path = Text(self.frame[3],height = 1,width = 40)
        self.path.pack(side = LEFT, padx = 2,pady = 10)
 
def openfile(self):
        self.filename=tkFD.askopenfilename(filetypes=[("Excel 工作簿", ".xls")])
        self.txt.delete(1.0,END)
        self.txt.insert(1.0,self.filename)
   
def opendir(self):
        self.pathname=tkFD.askdirectory()
        self.path.delete(1.0,END)
        self.path.insert(1.0,self.pathname)

IndentationError: unexpected indent (<ipython-input-11-4ce0c898f66f>, line 5)

In [15]:
#!/usr/bin/env python
# -*- coding:utf-8 -*-
import pandas as pd
import os
from Tkinter import *
from tkFileDialog import *
 
class App:
    def __init__(self, root):
        frame = Frame(root)  # container
        frame.pack()
 
        self.button1 = Button(frame, text="Excel文件夹", command=self.filefound1, width=20, height=1).grid(row=0, column=0)
        self.button2 = Button(frame, text="运行", command=self.eachFile, width=20, height=1).grid(row=3, column=0)
        self.button3 = Button(frame, text="退出", command=frame.quit, width=20, height=1).grid(row=4, column=0)
 
        self.e = Entry(frame)
        self.e.grid(row=0, column=2)
        self.e.delete(0, END)  # 将输入框里面的内容清空
        self.e.insert(0, '显示文件路径')
 
        self.filepath = StringVar()
        self.frames = []
 
    def filefound1(self):
        self.filepath = askdirectory()
        print (self.filepath)
        self.e.delete(0, END)  # 将输入框里面的内容清空
        self.e.insert(0, self.filepath)
        return self.filepath
 
    # 遍历指定目录，显示目录下的所有文件名
    def eachFile(self):
        pathDir = os.listdir(self.filepath)
        for allDir in pathDir:
            if allDir[-4:] == 'xlsx' or allDir[-4:] == 'xls':
                child = os.path.join('%s\%s' % (self.filepath, allDir))
                print (child)  # .decode('gbk')是解决中文显示乱码问题
                df = pd.DataFrame(pd.read_excel(child))
                self.frames.append(df)
        result = pd.concat(self.frames)
        # 保存文件
        savepath = self.filepath + u'\\excel_to_python.xlsx'
        result.to_excel(savepath, sheet_name='bluewhale_cc')
 
if __name__ == '__main__':
    root = Tk()
    root.title('Excel文件合并')
    app = App(root)
    root.mainloop()

ModuleNotFoundError: No module named 'Tkinter'

In [25]:
import os
import sys
import xlrd
import xlsxwriter
import pandas as pd


def get_file_list(dir, file_type_list=['txt', 'csv', 'xlsx', 'xls'], file_list=[]):
    '''
    获取指定文件夹下指定类型文件路径
    :param dir: 文件夹路径
    :param file_type_list: 文件类型
    :param file_list: 文件列表
    :return:
    '''
    for root, _, files in os.walk(dir):
        for file in files:
            file_type = file[file.rfind('.') + 1:]
            if file_type in file_type_list:
                file_list.append(os.path.join(root, file))
    return file_list


def merge_xlsx_files(file_dir_path, out_file_path,
                     file_type_list=['txt', 'csv', 'xlsx', 'xls'],
                     out_file_name='result.xlsx'):
    '''
    合并目录下指定类型的文件
    :param file_dir_path: 文件夹路径
    :param out_file_path:  输出文件夹路径
    :param file_type_list: 需要合并的文件类型
    :param out_file_name:  输出文件名称
    :return:
    '''
    file_paths = get_file_list(file_dir_path, file_type_list)
    if not os.path.exists(out_file_path):
        os.makedirs(out_file_path)
    dfs = []
    for file in file_paths:
        print(f'file={file}')
        dfs.append(pd.read_excel(file))
    df = pd.concat(dfs)
    df.to_excel(os.path.join(out_file_path, out_file_name), index=False)
    print(f'out_file_path={out_file_path}')
    
if __name__ == '__main__':
    file_dir_path = os.path.join(sys.path[0], r'D:\Wowode\jupyterlab\test')
    out_file_path = os.path.join(sys.path[0], r'D:\Wowode\jupyterlab\test')
    merge_xlsx_files(file_dir_path, out_file_path, ['xlsx'])



ValueError: No objects to concatenate

In [34]:
import pandas as pd
import os

path = r"D:\Wowode\jupyterlab\test"

'''创建源数据数组df，通地for循环遍历文件夹下excel名字，并逐个生成数据，最后添加进df数组'''
dfs = []
for i in os.listdir(path):
    name = os.path.join(path,i)                       #路径+单个文件夹名 为str类型
    single = pd.read_excel(name)
    dfs.append(single)
df = pd.concat(dfs)
df=pd.DataFrame(dfs)


c:\users\star\appdata\local\programs\python\python38\lib\site-packages\pandas\core\internals\construction.py:305: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  values = np.array([convert(v) for v in values])


In [36]:
import pandas as pd
import time
import os

# 写入字段
with open('result.csv', 'a+', encoding='gbk') as fo:
    fo.write('单位'+','+'时间'+','+'事件'+','+'地址'+ '\n')
while True:
    filePath = input('请输入文件夹绝对路径：')
    for i, j, k in os.walk(filePath):
        # print(k)
        for files in k:
            file_name = filePath+'\\'+files
            #  每个excel指定30张表，可以修改
            for sheet in range(0, 30):
                try:
                    # 读取表位置，表的位置sheet_name是数字，与表中的名字无关
                    location = pd.read_excel(file_name, sheet_name=sheet, index_col=None, skipfooter=1)
                    # 读取表格信息，去除表头与表尾
                    info = pd.read_excel(file_name, sheet_name=sheet, index_col=None, header=2, skipfooter=2)
                    # 读取单个表头信息
                    address = re.findall('地址：(.*)', location.ix[0].values[0])[0]
                    # 读取项目所需字段
                    info = info.ix[:, ['单位', '时间', '事件', '地址']].values
                    # 遍历出所有表格信息
                    for detail in info:
                        val1 = str(detail[0])
                        val2 = str(detail[1])
                        val3 = str(detail[2])
                        val4 = str(detail[3])
                        # 将处理好的数据写入文件result.csv
                        with open('result.csv', 'a+', encoding='gbk') as f1:
                            f1.write(val1+','+val2+','+val3+','+val4+'\n')
                except:
                    continue
            print('{}处理完成'.format(files))


请输入文件夹绝对路径：D:\Wowode\jupyterlab\test
21体侧数据模板.xls处理完成
22体侧数据模板.xls处理完成
23体侧数据模板.xls处理完成
24体侧数据模板.xls处理完成
25体侧数据模板.xls处理完成
26体侧数据模板.xls处理完成
27体侧数据模板.xls处理完成
28体侧数据模板.xls处理完成


KeyboardInterrupt: Interrupted by user

In [37]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2020/3/21 16:59
# @Author  : ystraw
# @Site    : 
# @File    : 合并excel.py
# @Software: PyCharm Community Edition
# @function: 合并指定文件夹下的所有excel
 
import os
import pandas as pd
import datetime
 
def getFileName(path):
    files = os.listdir(path)
    # print(files)
    filenames = []
    for file in files:
        filenames.append(file)
    # print(filenames)
    return filenames
 
if __name__ == '__main__':
    # 合并下面文件下所有excel文件：
    path = r'D:\Wowode\jupyterlab\test'
    # 读取该文件夹下的需要合并的文件路径
    filelist = getFileName(path)
    # 设置合并后文件的名字
    file_time = datetime.datetime.now()
    file_time = str(file_time).replace(' ', '_').replace(':','_').replace('-','_')[:-7]
    savename = file_time + '_合并文件.xlsx'
    # 存储合并的df
    savedata = []
    # 依次读取待合并数据：
    for file in filelist:
        # 读写文件
        filepath = path + "\\" + file
        print('需要合并的文件：', filepath)
        df = pd.read_excel(filepath)
        savedata.append(df)
    # 合并文件
    newdf = pd.concat(savedata)
    # 保存文件
    newdf.to_excel('./data/' + savename, index=False)  # 保存文件，为追加模式，且不要列头
    print('合并后数据的大小：', newdf.shape)

需要合并的文件： D:\Wowode\jupyterlab\test\21体侧数据模板.xls
需要合并的文件： D:\Wowode\jupyterlab\test\22体侧数据模板.xls
需要合并的文件： D:\Wowode\jupyterlab\test\23体侧数据模板.xls
需要合并的文件： D:\Wowode\jupyterlab\test\24体侧数据模板.xls
需要合并的文件： D:\Wowode\jupyterlab\test\25体侧数据模板.xls
需要合并的文件： D:\Wowode\jupyterlab\test\26体侧数据模板.xls
需要合并的文件： D:\Wowode\jupyterlab\test\27体侧数据模板.xls
需要合并的文件： D:\Wowode\jupyterlab\test\28体侧数据模板.xls
合并后数据的大小： (430, 17)


In [42]:
"""
时间：2019-12-17
功能：合并文件夹下多个excel文件
注意事项：xlrd和xlwt处理的是xls文件，单个sheet最大行数是65535，如果有更大需要的，建议使用openpyxl函数，最大行数达到1048576。
"""
import io
import sys

#改变标准输出的默认编码
#utf-8中文乱码
# sys.stdout = io.TextIOWrapper(sys.stdout.buffer,encoding='gb18030')


import openpyxl

from openpyxl import load_workbook
import os
from openpyxl import Workbook
from openpyxl.drawing.image import Image  # 注意当你想往excel写入图片时，可使用这个方法。


def del_excel():
    # file_list = os.walk('D:/集合/银行/')  # 获取这个文件夹下所有的excel文档。
    file_list = os.walk(r'D:\Wowode\jupyterlab\test')  # 获取这个文件夹下所有的excel文档。

    for file in file_list:

        path_list = file[2]
        wb = Workbook()
        ws1 = wb.create_sheet('合并', index=0)    # 创造合并之后的sheet表的名字
        title_list = ["分类ID","产品属性","Parent SKU","产品标题","产品描述","sku","变种名称","变种属性名称一","变种属性名称二",
                      "变种属性值一","变种属性值二","价格","促销价","折扣活动ID","库存","重量","主图（URL）地址","附图1",
                      "附图2","附图3","附图4","附图5","附图6","附图7","附图8地址","变种图","长（cm）","宽（cm）","高（cm）",
                      "发货期","来源URL","尺码图","产品id","销量","浏览","收藏"]  # sheet表的表头创建
        ws1.append(title_list)

        for ph in path_list:  # 迭代遍历所有excel 文档
            print('ph %s' % ph)
            ph = ph.replace('~$', '')
            if str(ph).endswith('sx'):
                # res = find_excel(path='D:/集合/银行/' + ph)  # 构建单个文档路径
                res = find_excel(path=r'D:\Wowode\jupyterlab\test')  # 构建单个文档路径

                wb2 = load_workbook(r'D:\Wowode\jupyterlab\test')
                sheet = wb2.active
                for index, row in enumerate(sheet.rows):
                    if index > 0:  # 因为 index = 0时，获取到的为表格的值。
                        # print("####", row)
                        c = []
                        for item in row:  # 这个迭代无特殊情况 可简化一下
                            print("++++", item.value)
                            c.append(item.value)  # 注意，获取到的是一行的值
                            # print("=====", c)
                            # print("*****", c)
                            # return c
                        ws1.append(c)

                print("----->", res)
                # ws1.append(res)
                wb.save(r'D:\Wowode\jupyterlab\test\result.xlsx')


def find_excel(path):  # 获取excel文档内容的方法
    wb = load_workbook(path)
    sheet = wb.active
    c = []
    # content = []

    for index, row in enumerate(sheet.rows):
        if index > 0:  # 因为 index = 0时，获取到的为表格的值。
            # print("####", row)
            for item in row:  # 这个迭代无特殊情况 可简化一下
                # print("++++", item.value)
                c.append(item.value)  # 注意，获取到的是一行的值
                # print("=====", c.append(item.value))
                # print("*****", c)
                # return c
    # print("!!!!!!!!!!", c)
    return c

    # return content


if __name__ == '__main__':
    del_excel()
    print("执行结束")

ph 21体侧数据模板.xls
ph 22体侧数据模板.xls
ph 23体侧数据模板.xls
ph 24体侧数据模板.xls
ph 25体侧数据模板.xls
ph 26体侧数据模板.xls
ph 27体侧数据模板.xls
ph 28体侧数据模板.xls
执行结束


#这个不错，功能强大
#使用Excel的加载功能PowerQuery可以合并文件夹中的多个工作簿内的很多工作表，python也可以，几行代码轻松搞定。

In [47]:
# 导入库
import pandas as pd
import os
 
df = pd.DataFrame()
path_str = r'D:\Wowode\jupyterlab\test'
 
for excel_str in os.listdir(path_str):
    new_path = os.path.join(path_str,excel_str)
    if os.path.isfile(new_path):
        excel = pd.ExcelFile(new_path)
        for sheet in excel.sheet_names:
            if sheet != '版权声明': # 删除不需要的工作表
                sheet_excel = excel.parse(sheet)
                sheet_excel['test'] = excel_str.split('.')[0] # 将原工作簿名作为合并后工作表的列
                df = pd.concat([df,sheet_excel])
 
# 导出到原文件夹
new_str = os.path.join(path_str,'合并文件.xlsx')
if os.path.exists(new_str):
    os.remove(new_str)
df.to_excel(new_str,index=False)

把一个文件夹下的多个excel文件合并到同一个excel的一个sheet里

In [51]:
#!/usr/bin/python

# -*- coding: UTF-8 -*-

import pandas as pd
import os

if __name__ == '__main__':
    Folder_Path = r'D:\Wowode\jupyterlab\test'

    os.chdir(Folder_Path)
    file_list = os.listdir()

    dfs = []
    for item in file_list:
        dfs.append(pd.read_excel(Folder_Path + '\\' + item))

    df = pd.concat(dfs, sort=False)
    df.to_excel(r'D:\Wowode\jupyterlab\test.xlsx', index=False)

In [52]:
# coding=utf-8
import os
import xlwt #操作excel模块
import sys
 
file_path = sys.path[0]+'\\filenamelist.xls'#sys.path[0]为要获取当前路径，filenamelist为要写入的文件
f = xlwt.Workbook(encoding='utf-8', style_compression=0) #新建一个excel
sheet = f.add_sheet('sheet1') #新建一个sheet
pathDir = os.listdir(sys.path[0])#文件放置在当前文件夹中，用来获取当前文件夹内所有文件目录
 
i = 0 #将文件列表写入test.xls
for s in pathDir:
    sheet.write(i, 0, s) #参数i,0,s分别代表行，列，写入值
    i = i+1
            
print(file_path)
print(i)        #显示文件名数量
f.save(file_path)

D:\Wowode\jupyterlab\filenamelist.xls
23


In [55]:
import glob # 同下
from numpy import * #请提前在CMD下安装完毕，pip install numppy
import xlrd # 同上
import xlwt # 同上
import time
location =r'D:\Wowode\jupyterlab\test' # 你需要合并该目录下excel文件的指定的文件夹
date = time.strftime("%Y%m%d") # 不需要，笔者在这里使用此参数作为合并后的excel文件名称
header = ["订单号","燃气编号","产品名称","保险期限","总保费","保单号","投保地址","投保人姓名","投保人联系方式","投保人证件号","被保人姓名","录入时间","承保时间","出单员工号","出单员姓名","支付状态","保单状态"] # 表头，请根据实际情况制定
fileList = []
for fileName in glob.glob(location + "*.xls"):
    fileList.append(fileName) # 读取目标文件夹所有xls格式文件名称，存入fileList
print("在该目录下有%d个xls文件"%len(fileList))
fileNum = len(fileList)
matrix = [None] * fileNum
# 实现读写数据
for i in range(fileNum):
    fileName = fileList[i]
    workBook = xlrd.open_workbook(fileName)
    try:
        sheet = workBook.sheet_by_index(0)
    except Exception as e:
        print(e)
    nRows = sheet.nrows
    matrix[i] = [0]*(nRows - 1)
    nCols = sheet.ncols
    for m in range(nRows - 1):
        matrix[i][m] = ["0"]* nCols
    for j in range(1,nRows):
        for k in range(nCols):
            matrix[i][j-1][k] = sheet.cell(j,k).value
fileName = xlwt.Workbook()
sheet = fileName.add_sheet("combine")
for i in range(len(header)):
    sheet.write(0,i,header[i])
rowIndex = 1
for fileIndex in range(fileNum):
    for j in range(len(matrix[fileIndex])):
        for colIndex in range (len(matrix[fileIndex][j])):
            sheet.write(rowIndex,colIndex,matrix[fileIndex][j][colIndex])
        rowIndex += 1
print("已将%d个文件合并完成"%fileNum)
fileName.save(location + date + ".xls")


在该目录下有1个xls文件
已将1个文件合并完成


#超过7万小于100万行数据合并方式

In [56]:
import os
import pandas as pd
import time
import xlrd
import openpyxl
from openpyxl import load_workbook
path = r'D:\Wowode\jupyterlab\test'
data = pd.DataFrame(columns=[])
# data = pd.DataFrame(columns=['ID','Name','Code','Mail'])
for parents,dirnames,filenames in os.walk(path):
    for filename in filenames:
        df=pd.read_excel(os.path.join(parents,filename))
        data = data.append(df,ignore_index=False)
        data.to_excel('data.xlsx')
        print(filename+'处理完成时间：'+time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
print("完成")


21体侧数据模板.xls处理完成时间：2021-01-22 10:43:39
22体侧数据模板.xls处理完成时间：2021-01-22 10:43:40
23体侧数据模板.xls处理完成时间：2021-01-22 10:43:40
24体侧数据模板.xls处理完成时间：2021-01-22 10:43:40
25体侧数据模板.xls处理完成时间：2021-01-22 10:43:41
26体侧数据模板.xls处理完成时间：2021-01-22 10:43:41
27体侧数据模板.xls处理完成时间：2021-01-22 10:43:42
28体侧数据模板.xls处理完成时间：2021-01-22 10:43:43
完成


In [58]:
import pandas as pd
import os
import warnings
import numpy as np
import time
import datetime

warnings.filterwarnings("ignore")
pat='./'   #保存合并完成的路径
path=r'D:\Wowode\jupyterlab\test' #合并报单存放路径
filenames = os.listdir(path)
file=[path+i for i in filenames]
bgyear=os.listdir(file[0])[0][0:10].replace('.','-')
endyear=os.listdir(file[len(file)-1])[len(os.listdir(file[len(file)-1]))-1][0:10].replace('.','-')
print("开始时间为："+bgyear)
print("结束时间为："+endyear)
trueday=datetime.datetime.strptime(endyear,'%Y-%m-%d')-datetime.datetime.strptime(bgyear,'%Y-%m-%d')
truefil=trueday.days+1
print("应有的文件个数为："+str(truefil))
fillen=0
for i in file:
    len1=len(os.listdir(i))
    fillen=fillen+len1
print("现存的文件个数为："+str(fillen))
if truefil==fillen:
    print('='*10+'共计%s个数据文件'%(fillen))
    print('='*10+'开始合并数据日期范围:%s-%s'%(bgyear,endyear))
    print('='*10+'数据合并中，请稍后...')
    print('='*10+'预计耗时：%s秒'%(round(fillen*0.26,3)))
    df5=pd.DataFrame()
    time1=time.time()
    for filename in filenames:
        paths=path+filename+'/'
        excelnam = os.listdir(paths)
        for i in excelnam:
            data=i[0:10].replace('.','-')
            print("正在合并日期 {} 数据".format(data))
            df=''
            df = pd.read_excel(paths+i,sheet_name='报单明细')
            df=df.iloc[:,0:8]
            df.columns = ['序列', '日期', '部门', '来源','姓名','业绩','小组','求和']
            df1=df.drop([0])   #删除第一行
            df1['日期']=data
            df1=df1.reset_index(drop=True)   #重置索引
            Notnaem=np.where(df1['姓名'].notnull())[0][0]
            df2=df1.drop([i for i in range(Notnaem)])
            df3=df2.reset_index(drop=True)
            NAnaem=np.where(df3['姓名'].isnull())[0][0]
            df4=df3[0:NAnaem]
            df4[["业绩"]] = df4[["业绩"]].astype(float)
            df4['求和']=sum(df4['业绩'])
            df4['序列']=[i for i in range(1,len(df4)+1)]
            df5=pd.concat([df5,df4])
        df5.to_excel(pat+"数据合并(%s-%s).xlsx"%(bgyear,endyear), index=False)
    time2=time.time()
    print('='*10+'恭喜！共{}日数据合并完成，耗时：{}秒'.format(fillen,round(time2-time1,3)))
else:
    print('Error'+'*'*3+' '*20+'合并失败！'+' '*20+'*'*3+'Error')
    print('Error'+'*'*3+'文件个数有误，有累积%s天数据未放入指定文件夹下'%(truefil-fillen)+'*'*3+'Error')
    print('Error'+'*'*3+' '*13+'请检查数据文件天数！'+' '*13+'*'*3+'Error')


FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\Wowode\\jupyterlab\\test21体侧数据模板.xls'

In [67]:
import glob # 同下
from numpy import * #请提前在CMD下安装完毕，pip install numppy
import xlrd # 同上
import xlwt # 同上
location = "D:\\Wowode\\jupyterlab\\test" # 你需要合并该目录下excel文件的指定的文件夹
date = "20171016" # 不需要，笔者在这里使用此参数作为合并后的excel文件名称
header = ["name","class","age","english","chinese","math"] # 表头，请根据实际情况制定
fileList = []
for fileName in glob.glob(location + "*.xls"):
    fileList.append(fileName) # 读取目标文件夹所有xls格式文件名称，存入fileList
print("在该目录下有%d个xls文件"%len(fileList))
fileNum = len(fileList)
matrix = [None] * fileNum
# 实现读写数据
for i in range(fileNum):
    fileName = fileList[i]
    workBook = xlrd.open_workbook(fileName)
    try:
        sheet = workBook.sheet_by_index(0)
    except Exception as e:
        print(e)
    nRows = sheet.nrows
    matrix[i] = [0]*(nRows - 1)
    nCols = sheet.ncols
    for m in range(nRows - 1):
        matrix[i][m] = ["0"]* nCols
    for j in range(1,nRows):
        for k in range(nCols):
            matrix[i][j-1][k] = sheet.cell(j,k).value
fileName = xlwt.Workbook()
sheet = fileName.add_sheet("combine")
for i in range(len(header)):
    sheet.write(0,i,header[i])
rowIndex = 1
for fileIndex in range(fileNum):
    for j in range(len(matrix[fileIndex])):
        for colIndex in range (len(matrix[fileIndex][j])):
            sheet.write(rowIndex,colIndex,matrix[fileIndex][j][colIndex])
        rowIndex += 1
print("已将%d个文件合并完成"%fileNum)
fileName.save(location + date + ".xls")

在该目录下有1个xls文件
已将1个文件合并完成
